---
- hosts: 172.31.0.172 
  become: yes
  tasks:
  - name: i want to execute direct linux command
    command: hostname -f
    register: myresult
  - name: display first task result
    debug:
       msg: "{{myresult}}"