---
- hosts: 172.31.0.172 
  become: yes
  tasks:
  - name: i want to execute direct linux command
    command: hostname -f
    register: myresult
  - name: display first task result
    debug:
       msg: "{{myresult}}"

  - name: install git
    apt: 
      name: git
      state: present
    when: myresult.stderr ==""

  - name: instll tree
    apt:
      name: tree
      state: present
    when: myresult.stderr !=""