---
- hosts: 172.31.0.172 
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
     name: apache2
     state: present

  - name:  i want to copy mytestfile into node side
    copy:
      src: mytestfile
      dest: /home/ubuntu/mytestfile

  - name:  i want to copy index.j2 file into node side
    template:
        src: myindex.j2
        dest: /var/www/html/index.html
    notify: restartwebserver
 
  handlers:
  - name: restartwebserver
    service:
       name: apache2
       state: restarted
  
